NDLANO/learningpath-api

build.sbt
Avhengig av ack og release av network
=> #174: Tatt ibruk ny generering av applicationUrl

src/main/scala/no/ndla/learningpathapi/service/UpdateServiceComponent.scala
=> #482 fixed response to return V2 when copying learningpath

src/main/scala/no/ndla/learningpathapi/model/domain/Language.scala, src/main/scala/no/ndla/learningpathapi/service/ConverterServiceComponent.scala, src/main/scala/no/ndla/learningpathapi/validation/LearningStepValidator.scala, src/test/scala/no/ndla/learningpathapi/validation/LearningStepValidatorTest.scala
This reverts commit e21fa9b0306e8760de22a6a91990710145fb7a2e.
=> Revert "no lanugage fallback on description|embedUrl #709"

.gitignore, build.sbt, src/main/scala/no/ndla/learningpathapi/controller/InternController.scala, src/main/scala/no/ndla/learningpathapi/controller/NdlaController.scala, src/main/scala/no/ndla/learningpathapi/model/api/LearningPathDomainDump.scala, src/main/scala/no/ndla/learningpathapi/repository/LearningPathRepositoryComponent.scala, src/main/scala/no/ndla/learningpathapi/service/ReadServiceComponent.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchIndexServiceComponent.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchServiceComponent.scala
Intern endpoint that dumps learningpaths for use with the `search-api`
=> #914: Intern dump domain learningpaths endpoint

build.sbt
resolves https://github.com/NDLANO/Issues/issues/948
=> #948: Removed unused dependency for security reasons

src/main/scala/no/ndla/learningpathapi/integration/Elastic4sClient.scala, src/main/scala/no/ndla/learningpathapi/model/domain/NDLAErrors.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchServiceComponent.scala
connects to https://github.com/NDLANO/Issues/issues/1177
=> #1177: Sets longer timeout for elastic4s client

src/main/scala/no/ndla/learningpathapi/integration/ArticleImportClient.scala
Fixes timeout when importing learningpaths
=> Increased timeout from 90 to 600 seconds.

src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala
Glemte å ha med dokumentasjon ¯\_(ツ)_/¯
=> Adds documentation for message on status update

src/main/scala/no/ndla/learningpathapi/model/domain/Language.scala, src/test/scala/no/ndla/learningpathapi/service/ImportServiceTest.scala
resolves https://github.com/NDLANO/Issues/issues/1414
=> #1414: Makes sure language is in languagePriority or unknown

src/main/scala/no/ndla/learningpathapi/service/search/SearchService.scala, src/test/scala/no/ndla/learningpathapi/service/search/SearchServiceTest.scala
=> #1436: Fixes search with language and fallback

build.sbt, src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala
connected to NDLANO/Issues#1439
=> update network library version #1439

src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala, src/main/scala/no/ndla/learningpathapi/service/ImportService.scala
Lets non-ndla-urls pass through import.
=> Support import urls in embed

src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala, src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala, src/main/scala/no/ndla/learningpathapi/controller/NdlaController.scala, src/main/scala/no/ndla/learningpathapi/model/api/Error.scala, src/main/scala/no/ndla/learningpathapi/model/api/SearchResult.scala, src/main/scala/no/ndla/learningpathapi/model/domain/SearchResult.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchConverterServiceComponent.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchService.scala, src/test/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2Test.scala, src/test/scala/no/ndla/learningpathapi/service/search/SearchServiceTest.scala
connects to NDLANO/Issues#1489
=> #1489: Implements scrolling for learningpath-search

src/main/scala/no/ndla/learningpathapi/controller/InternController.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchIndexService.scala, src/test/scala/no/ndla/learningpathapi/controller/InternControllerTest.scala
Connects to NDLANO/Issues#1532
=> #1532: Add delete index method

src/main/scala/no/ndla/learningpathapi/service/ImportService.scala
Some steps have / at the end of the url , and this blocks import of learningpath. Feel free to improve the code!
=> Stripping slash to fix import

src/main/scala/no/ndla/learningpathapi/controller/InternController.scala, src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala, src/main/scala/no/ndla/learningpathapi/controller/NdlaController.scala, src/main/scala/no/ndla/learningpathapi/model/search/SearchableLearningStep.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchConverterServiceComponent.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchIndexService.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchService.scala, src/test/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2Test.scala, src/test/scala/no/ndla/learningpathapi/service/search/SearchConverterServiceTest.scala, src/test/scala/no/ndla/learningpathapi/service/search/SearchServiceTest.scala
Legger til url i indeksen og legger til ny funksjon for å filtrere på dette. 
Dette skal brukes av draft-api for å sjekke om en artikkel er i bruk i en læringssti.
=> Search learningpaths for contained urls

README.md, src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala, src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala, src/main/scala/no/ndla/learningpathapi/model/api/SearchParams.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchIndexService.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchService.scala, src/test/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2Test.scala, src/test/scala/no/ndla/learningpathapi/service/search/SearchServiceTest.scala
Connects to Issues/NDLANO#1709
=> Verification status search

.travis.yml, build.sbt, pact.sbt, project/build.properties, project/plugins.sbt, src/main/scala/db/migration/V11__CreatedByNdlaStatusForOwnersWithRoles.scala, src/main/scala/no/ndla/learningpathapi/JettyLauncher.scala, src/main/scala/no/ndla/learningpathapi/repository/LearningPathRepositoryComponent.scala, src/test/scala/no/ndla/learningpathapi/TestData.scala, src/test/scala/no/ndla/learningpathapi/UnitSuite.scala, src/test/scala/no/ndla/learningpathapi/consumerdrivencontracts/LearningpathApiProviderCDCTest.scala
Depends on: NDLANO/search-api/pull/80
=> #1887: Setup pact verification against search-api

src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala, src/main/scala/no/ndla/learningpathapi/validation/LearningPathValidator.scala
Fixes NDLANO/Issues#2126
Learningpath is validated 9 lines below.
=> Remove redundant validation

build.sbt, src/main/scala/no/ndla/learningpathapi/integration/SearchApiClient.scala, src/main/scala/no/ndla/learningpathapi/integration/TaxonomyApiClient.scala, src/main/scala/no/ndla/learningpathapi/model/domain/Language.scala, src/main/scala/no/ndla/learningpathapi/model/domain/NDLAErrors.scala, src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala, src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchConverterServiceComponent.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchIndexService.scala, src/main/scala/no/ndla/learningpathapi/service/search/SearchService.scala, src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Fixes NDLANO/Issues#2270
Kjører også search-api indekseringen i en `Future` for å slippe å vente på den indekseringen ved hver lagring.
=> #2270: Update taxonomy if exists when saving learningpaths

src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala, src/main/scala/no/ndla/learningpathapi/integration/TaxonomyApiClient.scala, src/main/scala/no/ndla/learningpathapi/service/ImportService.scala, src/main/scala/no/ndla/learningpathapi/service/ReadService.scala, src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala, src/test/scala/no/ndla/learningpathapi/service/ImportServiceTest.scala, src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
=> #2312: Add endpoint for manually triggering taxonomy updates
